[buildPlans.mazer]
family = "Iosevka Custom"
spacing = "quasi-proportional-extension-only"
serifs = "sans"
no-cv-ss = false

  [buildPlans.mazer.variants]
  inherits = "ss09"

    [buildPlans.mazer.variants.design]
    capital-a = "curly-serifless"
    capital-b = "more-asymmetric-serifless"
    capital-c = "serifless"
    capital-d = "more-rounded-serifless"
    capital-e = "serifless"
    capital-f = "serifless"
    capital-g = "toothless-corner-inward-serifed-hooked"
    capital-h = "serifless"
    capital-i = "serifless"
    capital-j = "serifless"
    capital-k = "curly-serifless"
    capital-l = "serifless"
    capital-m = "slanted-sides-hanging"
    capital-n = "asymmetric"
    capital-p = "open"
    capital-q = "horizontal-tailed"
    capital-r = "standing"
    capital-s = "serifless"
    capital-t = "serifless"
    capital-u = "toothless-rounded"
    capital-v = "curly"
    capital-w = "curly"
    capital-x = "curly-serifless"
    capital-y = "curly-serifless"
    capital-z = "straight-serifless-with-horizontal-crossbar"
    a = "single-storey-earless-rounded-serifless"
    b = "toothless-rounded"
    c = "serifless"
    d = "toothless-rounded-serifless"
    e = "flat-crossbar"
    f = "flat-hook"
    g = "single-storey-serifless"
    h = "straight"
    i = "serifless"
    j = "serifless"
    k = "curly-serifless"
    l = "serifless"
    m = "earless-rounded-double-arch-short-leg"
    n = "earless-corner-straight"
    p = "earless-rounded"
    q = "earless-rounded-tailed"
    r = "earless-corner"
    s = "serifless"
    t = "flat-hook"
    u = "toothless-corner"
    v = "curly"
    w = "cursive"
    x = "curly-serifless"
    y = "cursive-flat-hook"
    z = "straight-serifless"
    long-s = "bent-hook-descending"
    eszet = "sulzbacher-descending"
    turn-v = "curly"
    lower-alpha = "crossing"
    lower-delta = "rounded"
    capital-gamma = "serifless"
    lower-iota = "tailed"
    lower-lambda = "curly"
    lower-mu = "tailed"
    lower-xi = "rounded"
    cyrl-capital-ze = "serifless"
    cyrl-ze = "serifless"
    cyrl-capital-ka = "curly-serifless"
    cyrl-ka = "curly-serifless"
    cyrl-el = "straight"
    cyrl-en = "serifless"
    cyrl-ef = "cursive"
    cyrl-che = "standard"
    cyrl-capital-u = "curly"
    cyrl-capital-ya = "curly"
    cyrl-ya = "curly-open"
    cyrl-yeri = "cursive"
    cyrl-yery = "cursive"
    zero = "slashed-split-oval"
    one = "no-base-flat-top-serif"
    two = "curly-neck"
    three = "two-arcs"
    four = "semi-open-non-crossing"
    five = "oblique-upper-left-bar"
    six = "straight-bar"
    seven = "curly-serifless"
    eight = "crossing"
    nine = "straight-bar"
    tilde = "low"
    asterisk = "hex-low"
    underscore = "high"
    pilcrow = "high"
    caret = "high"
    paren = "flat-arc"
    brace = "curly-flat-boundary"
    number-sign = "upright"
    ampersand = "closed"
    at = "fourfold-solid-inner-tall"
    dollar = "open-cap"
    cent = "through"
    percent = "rings-continuous-slash"
    bar = "natural-slope"
    lig-ltgteq = "flat"
    ascii-single-quote = "straight"
    ascii-grave = "straight"
    question = "smooth"
    punctuation-dot = "round"
    diacritic-dot = "round"

  [buildPlans.mazer.ligations]
  inherits = "dlig"

[buildPlans.mazer.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.mazer.weights.regular]
shape = 550  # Weight for glyph shapes.
menu  = 550  # Weight for the font's names.
css   = 550  # Weight for webfont CSS.
